[[ProtocolBuffers]]
arch = "aarch64"
git-tree-sha1 = "0536d8a57d6177722fb02ba2cd6a4858f0cf37bc"
os = "macos"

    [[ProtocolBuffers.download]]
    sha256 = "636225654efc46e0e4a18987ffb9eb87ebe773f77c0bed85cd6964d6924d9664"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffers_jll.jl/releases/download/ProtocolBuffers-v3.16.1+0/ProtocolBuffers.v3.16.1.aarch64-apple-darwin.tar.gz"
[[ProtocolBuffers]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cbe391c25a1b966b8ff647ebf8641164e15988bf"
libc = "glibc"
os = "linux"

    [[ProtocolBuffers.download]]
    sha256 = "c4a227cf9349753b2a4bd5c6225b5cad38ef24a298b66fccb67536e6554e06c6"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffers_jll.jl/releases/download/ProtocolBuffers-v3.16.1+0/ProtocolBuffers.v3.16.1.aarch64-linux-gnu-cxx11.tar.gz"
[[ProtocolBuffers]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2253b8ed4af859c2d3d37be8511398f9605925b9"
libc = "musl"
os = "linux"

    [[ProtocolBuffers.download]]
    sha256 = "a57fbbaa67b1e312ba65ae1edd72352503f86e9465cdad0691c3c08c929a4cfb"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffers_jll.jl/releases/download/ProtocolBuffers-v3.16.1+0/ProtocolBuffers.v3.16.1.aarch64-linux-musl-cxx11.tar.gz"
[[ProtocolBuffers]]
arch = "aarch64"
git-tree-sha1 = "8e172ec97359ff840aec964cfbbc54dff0aac3f6"
os = "freebsd"

    [[ProtocolBuffers.download]]
    sha256 = "972d5c16eb5261dbd5034cf71bfb4a061b1db4be224d1def7e2812d24df45979"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffers_jll.jl/releases/download/ProtocolBuffers-v3.16.1+0/ProtocolBuffers.v3.16.1.aarch64-unknown-freebsd.tar.gz"
[[ProtocolBuffers]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef0983e6f8516ca0319155c5d8dc0dfd3b7e22df"
libc = "glibc"
os = "linux"

    [[ProtocolBuffers.download]]
    sha256 = "11c5c08a8bc1a58fc13c785506d6b92d8264460846f296928ca31f958bbcd0f0"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffers_jll.jl/releases/download/ProtocolBuffers-v3.16.1+0/ProtocolBuffers.v3.16.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ProtocolBuffers]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ada871a31f38b060b5b42e67eed81e272d274880"
libc = "musl"
os = "linux"

    [[ProtocolBuffers.download]]
    sha256 = "3f6440f78f107fae7ed34338be85f1852d6da4e4e5b1185d38cc13b4220bb371"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffers_jll.jl/releases/download/ProtocolBuffers-v3.16.1+0/ProtocolBuffers.v3.16.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ProtocolBuffers]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71bea34980b5bd112b5e7ddc84e4fcf014356651"
libc = "glibc"
os = "linux"

    [[ProtocolBuffers.download]]
    sha256 = "d0dbc251a64143fe18825b6e5f5ecaaf0f4b084366ef7ae39f3576fdf32e4197"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffers_jll.jl/releases/download/ProtocolBuffers-v3.16.1+0/ProtocolBuffers.v3.16.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ProtocolBuffers]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a945ee762fce72cf01a1a11296d00a8e45fb8926"
libc = "musl"
os = "linux"

    [[ProtocolBuffers.download]]
    sha256 = "50fc63db8b63f278a40fef9b8c154de0d054da6164b7cf82f2ef694b31bb363e"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffers_jll.jl/releases/download/ProtocolBuffers-v3.16.1+0/ProtocolBuffers.v3.16.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ProtocolBuffers]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e572edd5684bd30e16525928d646459485c11ef"
libc = "glibc"
os = "linux"

    [[ProtocolBuffers.download]]
    sha256 = "1adebed53e494d833b4b40dc34df4faaafa02f3f33e374e50270f4742501742f"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffers_jll.jl/releases/download/ProtocolBuffers-v3.16.1+0/ProtocolBuffers.v3.16.1.i686-linux-gnu-cxx11.tar.gz"
[[ProtocolBuffers]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ad897a057b498403366faecd6a59e5c3144b67a6"
libc = "musl"
os = "linux"

    [[ProtocolBuffers.download]]
    sha256 = "585f9c10096244d299341b7dac3b6df37e0f2ac8c0c500a98653898c0c3eb6b3"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffers_jll.jl/releases/download/ProtocolBuffers-v3.16.1+0/ProtocolBuffers.v3.16.1.i686-linux-musl-cxx11.tar.gz"
[[ProtocolBuffers]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e60482653969a23b6f8ac184e1d52fe0ac116873"
os = "windows"

    [[ProtocolBuffers.download]]
    sha256 = "de80a2a765dcb9364c1099e8648a29cee93258c00627bdfe61b87a574c37e34d"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffers_jll.jl/releases/download/ProtocolBuffers-v3.16.1+0/ProtocolBuffers.v3.16.1.i686-w64-mingw32-cxx11.tar.gz"
[[ProtocolBuffers]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e448a0bfb7a0a6763e659f6dc340c21b5483c2c1"
libc = "glibc"
os = "linux"

    [[ProtocolBuffers.download]]
    sha256 = "4ccf7ffaa9db3b0c903b0975218a070a0d20e7cd82e3547d20879ee95eb43d44"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffers_jll.jl/releases/download/ProtocolBuffers-v3.16.1+0/ProtocolBuffers.v3.16.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ProtocolBuffers]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a199bb54aebbedd44cc73cb7378fbf4b1957204"
libc = "glibc"
os = "linux"

    [[ProtocolBuffers.download]]
    sha256 = "3d2b96eecb1686204aa6451db69cbcb87bb5252652481de354be864b0de93a03"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffers_jll.jl/releases/download/ProtocolBuffers-v3.16.1+0/ProtocolBuffers.v3.16.1.riscv64-linux-gnu-cxx11.tar.gz"
[[ProtocolBuffers]]
arch = "x86_64"
git-tree-sha1 = "62abbcaaa780336b3bde3b0fb77a6fc01c829913"
os = "macos"

    [[ProtocolBuffers.download]]
    sha256 = "3066f1c3c2f2736e45c11ed56177fed937ad3d52e0b65bbc2216ff918f19b5c3"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffers_jll.jl/releases/download/ProtocolBuffers-v3.16.1+0/ProtocolBuffers.v3.16.1.x86_64-apple-darwin.tar.gz"
[[ProtocolBuffers]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f262c9b07d3830dbccd86462414ca5e62c6a3d4e"
libc = "glibc"
os = "linux"

    [[ProtocolBuffers.download]]
    sha256 = "a9e8622de7433b65896878d421633373833eab2acb637685bffb9bdfd46d6cf5"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffers_jll.jl/releases/download/ProtocolBuffers-v3.16.1+0/ProtocolBuffers.v3.16.1.x86_64-linux-gnu-cxx11.tar.gz"
[[ProtocolBuffers]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "23461259df16bf22fc6bed669509c2849136d2a4"
libc = "musl"
os = "linux"

    [[ProtocolBuffers.download]]
    sha256 = "c4a5da2c4b0e1a64fe5d58bcb684bcf038485d3a8bd800fb65038b9877219b7e"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffers_jll.jl/releases/download/ProtocolBuffers-v3.16.1+0/ProtocolBuffers.v3.16.1.x86_64-linux-musl-cxx11.tar.gz"
[[ProtocolBuffers]]
arch = "x86_64"
git-tree-sha1 = "6f0bb8abc05804e85025366413c09dd8a22f596d"
os = "freebsd"

    [[ProtocolBuffers.download]]
    sha256 = "94751d80237dae0c015fd249f0ea15488704b83adffb709b56163c3331f0fdd5"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffers_jll.jl/releases/download/ProtocolBuffers-v3.16.1+0/ProtocolBuffers.v3.16.1.x86_64-unknown-freebsd.tar.gz"
[[ProtocolBuffers]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f9f504a38d8739f28ac9ecca3522670efbd3c10f"
os = "windows"

    [[ProtocolBuffers.download]]
    sha256 = "0e94e690f030b187e90cc14e154e29c9c9257c05cd48da622bad36536ee36394"
    url = "https://github.com/JuliaBinaryWrappers/ProtocolBuffers_jll.jl/releases/download/ProtocolBuffers-v3.16.1+0/ProtocolBuffers.v3.16.1.x86_64-w64-mingw32-cxx11.tar.gz"
